<!DOCTYPE html>
<html>
 
<head>
    <meta charset=utf-8>
    <meta name=viewport content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
    <meta name=apple-mobile-web-app-capable content=yes>
    <meta name=theme-color content=#22549C>
    <meta name="description" content="รหัสพร้อมไป 10906373 ตำรวจตะเวนชายแดน 261 สำนักงานตำรวจแห่งชาติ ถนนทางหลวงแผ่นดินหมายเลข 201 ต.กุดป่อง อ.เมืองเลย จ.เลย 42000 ประเทศไทย Royal police loei National Highway 201 Rd., Kut Pong, Mueang Loei, Loei 42000 Thailand">
    <meta name="keywords" content="พร้อมไป, PromptPai, ตำรวจตะเวนชายแดน 261 สำนักงานตำรวจแห่งชาติ, Royal police loei">
    <meta name="user_agent" content="Android browser">
    <meta property="fb:app_id" content="148173948530677">
    <meta property="og:site_name" content="PromptPai">
    <meta property="og:image" content="https://map.longdo.com/image/ooi/1500892/730x382">
    <meta property="og:image:type" content="image/png">
    <meta property="og:url" content="https://promptpai.com/p/10906373">
    <meta property="og:description" content="รหัสพร้อมไป 10906373 ตำรวจตะเวนชายแดน 261 สำนักงานตำรวจแห่งชาติ ถนนทางหลวงแผ่นดินหมายเลข 201 ต.กุดป่อง อ.เมืองเลย จ.เลย 42000 ประเทศไทย Royal police loei National Highway 201 Rd., Kut Pong, Mueang Loei, Loei 42000 Thailand">
    <meta property="og:title" content="ตำรวจตะเวนชายแดน 261 สำนักงานตำรวจแห่งชาติ : พร้อมไป (PromptPai)">
    <meta property="og:type" content="place">
    <meta property="place:location:latitude" content="17.487057">
    <meta property="place:location:longitude" content="101.721671">
    <title>ตำรวจตะเวนชายแดน 261 สำนักงานตำรวจแห่งชาติ : พร้อมไป (PromptPai)</title>
    <link rel=apple-touch-icon href=/static/image/promptpai_app_icon_xxxhdpi.png>
    <link rel=apple-touch-startup-image href=/static/image/promptpai_app_icon_xxxhdpi.png>
    <link rel=apple-mobile-web-app-status-bar-style content=default>
    <link rel=apple-mobile-web-app-title content=PromptPai>
    <link rel=manifest href=/manifest.json>
    <link rel="shortcut icon" type=image/png href=/static/image/pp_icon256.png>
    <script language=JavaScript type=text/javascript src=https://www.longdo.com/api></script>
    <script src="https://api.longdo.com/map/?key=promptpai"></script>
    <script src="https://static.line-scdn.net/liff/edge/2.1/liff.js"></script>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-143787399-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
 
        function gtag() {
            dataLayer.push(arguments);
        }
        gtag("js", new Date());
        gtag("config", "UA-143787399-1");
    </script>
    <script type=application/ld+json>
        {
            "@context": "https://schema.org",
            "@type": "WebSite",
            "url": "https://promptpai.com/",
            "potentialAction": [{
                "@type": "SearchAction",
                "target": "https://promptpai.com/map/search/{search_term_string}/@13.764955,100.538317,12,1,0",
                "query-input": "required name=search_term_string"
            }]
        }
    </script>
    <link href=/static/css/app.21b9802879c278cbd62640c177ae52f8.css rel=stylesheet>
</head>
 
<body>
    <div id=app></div>
    <script type=text/javascript src=/static/js/manifest.0d8422026771e35f07c6.js></script>
    <script type=text/javascript src=/static/js/vendor.6a3ee3d72eee317a279b.js></script>
    <script type=text/javascript src=/static/js/app.a0359ed3a1d761d3695c.js></script>
</body>
 
</html>
